services:
  web:
    build: .
    # Kodda değişiklik yaparsan container'ı yeniden başlatmadan gör diye volume bağlıyoruz
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # İstersen environment değişkenlerini buraya ekleyebilirsin
    # environment:
    #   - DEBUG=False